from __future__ import annotations

from enum import StrEnum


class SourceClass(StrEnum):
    OBSERVED_OFFICIAL = "OBSERVED_OFFICIAL"
    OBSERVED_CANONICAL = "OBSERVED_CANONICAL"
    OBSERVED_LICENSED = "OBSERVED_LICENSED"
    ESTIMATED_MODEL = "ESTIMATED_MODEL"
    INFERRED_RESEARCH = "INFERRED_RESEARCH"
    TIER2_DISCOVERY = "TIER2_DISCOVERY"
    REJECTED = "REJECTED"


class SignalFamily(StrEnum):
    SUPERCYCLE_THESIS = "SUPERCYCLE_THESIS"
    SEC_FILINGS_OWNERSHIP = "SEC_FILINGS_OWNERSHIP"
    FINRA_SHORT_INTEREST = "FINRA_SHORT_INTEREST"
    CFTC_TFF_POSITIONING = "CFTC_TFF_POSITIONING"
    FRED_MACRO_LIQUIDITY = "FRED_MACRO_LIQUIDITY"
    KEN_FRENCH_FACTOR_CONTEXT = "KEN_FRENCH_FACTOR_CONTEXT"
    PRICE_VOLUME_BEHAVIOR = "PRICE_VOLUME_BEHAVIOR"
    IV_VOL_INTELLIGENCE = "IV_VOL_INTELLIGENCE"
    OPTIONS_WHALE_RADAR = "OPTIONS_WHALE_RADAR"
    GAMMA_DEALER_MAP = "GAMMA_DEALER_MAP"
    ROTATION_SCORE = "ROTATION_SCORE"
    ETF_PASSIVE_FLOW = "ETF_PASSIVE_FLOW"
    DARK_POOL_BLOCK_RADAR = "DARK_POOL_BLOCK_RADAR"
    MICROSTRUCTURE_LIQUIDITY = "MICROSTRUCTURE_LIQUIDITY"
    NEWS_NARRATIVE_VELOCITY = "NEWS_NARRATIVE_VELOCITY"
    RISK_INVALIDATION = "RISK_INVALIDATION"


class ConfidenceLabel(StrEnum):
    OBSERVED_CONTEXT = "OBSERVED_CONTEXT"
    CANONICAL_BEHAVIOR = "CANONICAL_BEHAVIOR"
    LICENSED_REQUIRED = "LICENSED_REQUIRED"
    ESTIMATED_CONTEXT = "ESTIMATED_CONTEXT"
    INFERRED_RESEARCH_ONLY = "INFERRED_RESEARCH_ONLY"
    REJECTED_FOR_STATE_ADVANCE = "REJECTED_FOR_STATE_ADVANCE"
