from __future__ import annotations

from enum import StrEnum


class OpportunityState(StrEnum):
    IGNORE = "IGNORE"
    THEME_WATCH = "THEME_WATCH"
    THESIS_CANDIDATE = "THESIS_CANDIDATE"
    EVIDENCE_BUILDING = "EVIDENCE_BUILDING"
    LEFT_SIDE_RISK = "LEFT_SIDE_RISK"
    ACCUMULATION_WATCH = "ACCUMULATION_WATCH"
    CONFIRMATION_WATCH = "CONFIRMATION_WATCH"
    BUYING_RANGE = "BUYING_RANGE"
    ADD_ON_SETUP = "ADD_ON_SETUP"
    LET_WINNER_RUN = "LET_WINNER_RUN"
    TRIM_OPTIONAL = "TRIM_OPTIONAL"
    CROWDED_FROTHY = "CROWDED_FROTHY"
    EXIT_RISK = "EXIT_RISK"
    THESIS_BROKEN = "THESIS_BROKEN"


class ReasonCode(StrEnum):
    THESIS_EVIDENCE = "THESIS_EVIDENCE"
    PRICE_VOLUME_BEHAVIOR = "PRICE_VOLUME_BEHAVIOR"
    IV_VOL_BEHAVIOR = "IV_VOL_BEHAVIOR"
    OPTIONS_WHALE_BEHAVIOR = "OPTIONS_WHALE_BEHAVIOR"
    SHORT_SQUEEZE_BASE = "SHORT_SQUEEZE_BASE"
    CTA_SYSTEMATIC_CONTEXT = "CTA_SYSTEMATIC_CONTEXT"
    ROTATION_CONTEXT = "ROTATION_CONTEXT"
    MACRO_LIQUIDITY_CONTEXT = "MACRO_LIQUIDITY_CONTEXT"
    FACTOR_REGIME_CONTEXT = "FACTOR_REGIME_CONTEXT"
    OWNERSHIP_WHALE_CONTEXT = "OWNERSHIP_WHALE_CONTEXT"
    RISK_INVALIDATION = "RISK_INVALIDATION"
