"""Write SAW round2_9 report."""
saw = (
    "# SAW Report - Phase 21 Round 2.9 Patch B (Expanded Anchor + MahDist Ceiling)\n"
    "Date: 2026-02-21\n\n"
    "Builds on prior rounds: docs/saw_phase21_round2_7.md, docs/saw_phase21_round2_8.md\n\n"
    "Hierarchy Confirmation: Approved | Session: current-thread | Trigger: patch-b-expanded-anchor-mahdist-ceiling | Domains: Backend, Data | FallbackSource: docs/spec.md + docs/phase_brief/phase21-brief.md\n\n"
    "RoundID: R21_PATCH_B_20260221\n"
    "ScopeID: S21_PATCHB_R29\n\n"
    "## Scope and Ownership\n"
    "- Scope: Patch B - expanded anchor basket + hard MahDist ceiling (<=5.0) + r_cyc_multi ranking.\n"
    "- Data injection: run_update(scope=Custom, custom_list=LRCX,AMAT,KLAC,STX,WDC) -> success, 6 tickers patched (live layer; STX/WDC absent from WRDS base, not present on 2024-12-24).\n"
    "- Effective anchor basket on 2024-12-24: MU, CIEN, LRCX, AMAT, KLAC (N=5; COHR, TER, STX, WDC absent from universe on this date).\n"
    "- Applied in strategies/ticker_pool.py:\n"
    "  1. seed_tickers extended: (MU, CIEN, COHR, TER, LRCX, AMAT, KLAC, STX, WDC)\n"
    "  2. Scoring block: r_cyc_multi = R[:,k_cyc_components].sum(axis=1), above-uniform threshold (> 1/3)\n"
    "  3. Hard ceiling: valid = mah_dist_cyc <= 5.0; score = where(valid and odds_ratio > 0.5, odds_ratio, -9999.0)\n"
    "- Owned files: strategies/ticker_pool.py, data/processed/phase21_1_ticker_pool_sample.csv, data/processed/phase21_1_ticker_pool_summary.json, docs/saw_phase21_round2_9.md\n\n"
    "## Harper Verbatim Gate (Round 2.9)\n"
    "PROMOTE only if the Top-8 ranked by score contains MU-style >=4 with explicit MU and CIEN present, defensives <=25%, PLUG/TZA = 0, and deep-space anomalies = 0 (no selected ticker with MahDist > 5.0).\n\n"
    "## Findings Table\n"
    "| Severity | Impact | Fix | Owner | Status |\n"
    "|---|---|---|---|---|\n"
    "| High | CSCO/USO/WBA still saturate (score=49999999) with r_cyc_multi near 1.0. MahDist ceiling correctly vetoed SMCI/NVDL/NBIS. MU is LONG but ranks below saturation tier. | Root cause: CSCO/USO/WBA have near-100% cyclical responsibility independently of anchor basket - structural BGM posterior issue. | Strategy | Open |\n"
    "| High | Explicit MU and CIEN absent from top-8. MU ranks 9th+; CIEN junk-dominant (action=WAIT). | CIEN impasse escalated to orchestrator. | Orchestrator | Open - Escalated |\n"
    "| Medium | PLUG still in top-8 (score=24.71, MahDist=3.78 passes ceiling filter but fails PLUG/TZA gate). | Requires explicit PLUG exclusion or posterior shift. | Strategy | Open |\n"
    "| Low | Deep-space violations: 0. MahDist ceiling working correctly. | Ceiling fix confirmed effective. | Strategy | Closed |\n"
    "| Low | mu_style_count_top8 = 1 (AVGO). Sentinel -9999 pushed SMCI/NVDL/NBIS out. | Still short of >=4 gate. | Strategy | Open |\n\n"
    "## Check Results\n"
    "- CHK-671: PASS (run_update Custom LRCX,AMAT,KLAC,STX,WDC -> success, 6 tickers)\n"
    "- CHK-672: PASS (seed_tickers extended in TickerPoolConfig)\n"
    "- CHK-673: PASS (Patch B scoring block applied to strategies/ticker_pool.py)\n"
    "- CHK-674: PASS (2024-12-24 slice rerun, exit code 0)\n"
    "- CHK-675: PASS (py_compile touched files)\n"
    "- CHK-676: PASS (pytest tests/test_ticker_pool.py -q -> 5 passed, 0 failed)\n"
    "- CHK-677: FAIL (Harper verbatim gate overall)\n\n"
    "ChecksTotal: 7\n"
    "ChecksPassed: 6\n"
    "ChecksFailed: 1\n\n"
    "## Gate Telemetry (2024-12-24)\n\n"
    "Top-8 LONG table (ranked by score = odds_ratio after MahDist ceiling):\n"
    "| Rank | Ticker | Score/OddsRatio | CompounderProb | MahDist_k_cyc |\n"
    "|------|--------|-----------------|----------------|---------------|\n"
    "| 1 | CSCO | 49,999,999 | 0.4076 | 1.3937 |\n"
    "| 2 | USO | 49,999,999 | 0.3503 | 1.4359 |\n"
    "| 3 | WBA | 49,999,999 | 0.2611 | 2.0941 |\n"
    "| 4 | PLUG | 24.71 | 0.0955 | 3.7751 |\n"
    "| 5 | AVGO | 13.29 | 0.1146 | 3.7345 |\n"
    "| 6 | LCID | 13.04 | 0.2166 | 2.3772 |\n"
    "| 7 | BB | 12.92 | 0.1210 | 3.6576 |\n"
    "| 8 | NVAX | 12.61 | 0.1465 | 2.7189 |\n\n"
    "Gate criterion results:\n"
    "- MU-style count top-8: 1 (AVGO) -- FAIL, need >=4\n"
    "- Explicit MU in top-8: False -- FAIL (MU action=LONG, ranks ~9th)\n"
    "- Explicit CIEN in top-8: False -- FAIL (CIEN junk-dominant, ESCALATED TO ORCHESTRATOR)\n"
    "- Defensives <=25% top-8: 0.0% -- PASS\n"
    "- PLUG/TZA count: 1 (PLUG, MahDist=3.78 passes ceiling) -- FAIL, need = 0\n"
    "- Deep-space MahDist>5.0 count: 0 -- PASS (ceiling filter working)\n"
    "- Min OddsRatio top-8: 12.61 -- PASS (>=3.0)\n\n"
    "Progress vs prior rounds:\n"
    "- Round 2.7: deep_space=4, mu_style=1, MU absent -- BLOCK\n"
    "- Round 2.8: deep_space=3, mu_style=2, MU absent -- BLOCK\n"
    "- Round 2.9: deep_space=0 (FIXED), mu_style=1, MU absent -- BLOCK\n\n"
    "## CIEN Escalation (Section 3 Upstream Investigation Required)\n"
    "CIEN on 2024-12-24: posterior_cyclical=0.394, posterior_junk=0.425, action=WAIT.\n"
    "Even with N=5 anchor basket, CIEN odds_ratio < 1.0 (junk-dominant).\n"
    "Orchestrator options:\n"
    "- Option 1 (Waive): Accept CIEN absent for 2024-12-24; gate passes if MU + 3 other MU-style anchors present.\n"
    "- Option 2 (Investigate): Check CIEN ebitda_accel, roic_accel, quality_lag, revenue_growth_q on 2024-12-24 for pipeline misalignment or stale fundamental input.\n\n"
    "## Scope Split Summary\n"
    "in-scope findings/actions:\n"
    "- Patch B applied. Data injection via run_update. MahDist ceiling confirmed effective (deep_space=0). py_compile PASS. pytest 5/5 PASS.\n"
    "inherited out-of-scope:\n"
    "- CSCO/USO/WBA saturation tier persists. PLUG MahDist below ceiling (3.78). CIEN structural impasse.\n\n"
    "## Evidence\n"
    "- Data injection: run_update(scope=Custom, custom_list=LRCX,AMAT,KLAC,STX,WDC) -> success, tickers_updated=6\n"
    "- Slice: .venv/Scripts/python scripts/phase21_1_ticker_pool_slice.py --start-date 2024-01-01 --as-of-date 2024-12-24\n"
    "- Compile: PASS. Tests: 5 passed, 0 failed.\n"
    "- CSV: data/processed/phase21_1_ticker_pool_sample.csv\n"
    "- JSON: data/processed/phase21_1_ticker_pool_summary.json\n\n"
    "SAW Verdict: BLOCK\n\n"
    "Open Risks:\n"
    "- CSCO/USO/WBA saturation (r_cyc_multi near 1.0) persists - structural BGM posterior issue unresolved.\n"
    "- PLUG (MahDist=3.78) passes MahDist ceiling but fails PLUG/TZA gate.\n"
    "- CIEN junk-dominance on 2024-12-24 - escalated to orchestrator.\n"
    "- MU cannot break into top-8 while CSCO/USO/WBA saturation tier occupies ranks 1-3.\n\n"
    "Next action: Patch B complete - paused, no other changes. Await orchestrator GO/ABORT/DIAGNOSE/WAIVE-CIEN decision.\n\n"
    "ClosurePacket: RoundID=R21_PATCH_B_20260221; ScopeID=S21_PATCHB_R29; ChecksTotal=7; ChecksPassed=6; ChecksFailed=1; Verdict=BLOCK; OpenRisks=CSCO_USO_WBA_saturation PLUG_in_top8 CIEN_escalated MU_below_saturation_tier; NextAction=paused await orchestrator decision\n"
    "ClosureValidation: PASS\n"
    "SAWBlockValidation: PASS\n"
)
with open("docs/saw_phase21_round2_9.md", "w", encoding="utf-8") as f:
    f.write(saw)
print("SAW round2_9 written:", len(saw.splitlines()), "lines")
